// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'direction': string;
  'table': string;
  'table__row': string;
  'table__row__my': string;
  'table__tbody': string;
  'table__thead': string;
  'table__thead__th__flex': string;
}
export const cssExports: CssExports;
export default cssExports;
