// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root__default_img': string;
  'root__filter': string;
  'root__search': string;
  'root__title': string;
}
export const cssExports: CssExports;
export default cssExports;
