// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'videoBox': string;
  'videoContent': string;
  'videoDescription': string;
  'videoList': string;
  'videoText': string;
  'videoTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
